name = "trickortreat-api"
main = "cloudflare-worker.js"
compatibility_date = "2023-10-30"

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "trickortreat-markers"
preview_bucket_name = "trickortreat-markers-preview"

# Environment variables (set these in Cloudflare dashboard)
[env.production.vars]
ALLOWED_ORIGINS = "https://yourdomain.com,https://localhost:3000"

[env.development.vars]
ALLOWED_ORIGINS = "*"

# Custom domains (optional)
routes = [
  { pattern = "trickortreat-api.yourdomain.com/*", zone_name = "yourdomain.com" }
]